### ISSUE TITLE
launching with the mod crash the game

### ISSUE THREAD

**Issue by Pi3tro88** [hp3721/masaadditions#11]
the minecraft version is not specified so i tested in 1.17.1 and 1.18.1 but it still crash the game (it doesnt start at all)

1.18.1 log:
[latest.log](https://github.com/hp3721/masaadditions/files/7963368/latest.log)

 1.17.1 log:
[latest.log](https://github.com/hp3721/masaadditions/files/7963360/latest.log)

**Comment by DragonEggBedrockBreaking** [comment]
You need to compile the 1.17/1.18 branches yourself if you want to use the mod there - the release version only works on 1.16…

**Comment by Pi3tro88** [comment]
uhhhhh ok thanks, there will be the update to 1.17/1.18?

**Comment by hp3721** [comment]
It has already been updated to 1.17 and 1.18 clone the proper branch and follow the build instructions in the [README](https://github.com/hp3721/masaadditions/blob/master/README.md).

**Comment by Pi3tro88** [comment]
oh okay thanks
