### ISSUE TITLE
1.17.1

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [hp3721/masaadditions#2]
Will this be updated to 1.17.1?

**Comment by hp3721** [comment]
Most of it is already ported to 1.17 in a local branch, but not sure when I will finish everything since I currently have a lack of interest for MC.

**Comment by hp3721** [comment]
The add-on has been ported to 1.17.1 in the `masaadditions-1.17` branch. The only missing feature in the port currently is the beacon range overlay being rendered whenever the player holds a beacon in their hand with the overlay renderer enabled.
