### ISSUE TITLE
Bit predictable, but doesn't work with the just-released 1.18 Tweakaroo

### ISSUE THREAD

**Issue by kkellogg378** [hp3721/masaadditions#6]
Game crashes when the game opens. I didn't expect it to work considering 1.18 Tweakaroo literally just got released, but here's to hoping a working version will be out soon :)

**Comment by hp3721** [comment]
It is expected that the mod won't work with the latest release without any changes. I plan on waiting for MiniHUD to release for 1.18 before I push my local commits to the [1.18 branch](https://github.com/hp3721/masaadditions/tree/masaadditions-1.18).

**Comment by DragonEggBedrockBreaking** [comment]
all the mods, including minihud and tweakeroo, have been released for 1.18.1

**Comment by hp3721** [comment]
@kkellogg378 @DragonEggBedrockBreaking The mod has been updated for 1.18.1.
