### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [hp3721/masaadditions#7]
[This is the error in logs](https://gist.github.com/DragonEggBedrockBreaking/06381ce5d06ddd15b2a12fbbc58b26da).
Compiled from masadditions-1.18 branch.
It works fine in a dev env, with `runClient`.
Crashes on both 1.18.1 and 22w03a.

**Comment by hp3721** [comment]
Are you using [WeirdAddons](https://github.com/fxmorin/WeirdAddons)? Try using the add-on with only Masa's mods.

**Comment by DragonEggBedrockBreaking** [comment]
> Are you using [WeirdAddons](https://github.com/fxmorin/WeirdAddons)?
Yes, are they incompatible?

**Comment by hp3721** [comment]
Possibly? That error seems to be from one of [WeirdAddons](https://github.com/fxmorin/WeirdAddons)'s mixins. Does it crash if you only use [WeirdAddons](https://github.com/fxmorin/WeirdAddons)?

**Comment by DragonEggBedrockBreaking** [comment]
> Possibly? That error seems to be from one of [WeirdAddons](https://github.com/fxmorin/WeirdAddons)'s mixins. Does it crash if you only use [WeirdAddons](https://github.com/fxmorin/WeirdAddons)?

The mod does not occur if you remove masaaddition, so it must be an incompatibility. Thanks for the quick fix!
